service: final-python-thumbnail

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1 
  profile: serverless-admin
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    THUMBNAIL_SIZE: 128
    REGION_NAME: ${self:provider.region}
  iam:
    role: 
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'

custom:
  bucket: matheus-thumbnail
  pythonRequirements:
    dockerizePip: true

functions:
  s3_thumbnail_generator:
    handler: handler.s3_thumbnail_generator
    layers:
      - arn:aws:lambda:sa-east-1:770693421928:layer:Klayers-p38-Pillow:3
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png

plugins:
  - serverless-python-requirements
